### ISSUE TITLE
Status update

### ISSUE THREAD

**Issue by berto0** [max13fr/Airzonecloud-HomeAssistant#1]
First, thank you for the work.
Second, I use Google Translate.

I am using the integration with Home Assistant, and I have detected that the temperature status is not updated. It is only updated when I enter the Airzone Cloud APP or modify the set point temperature from HA.

Thank you

**Comment by max13fr** [comment]
Hello,

Thanks for you report, I found the issue, I will fix it soon.

Max

**Comment by max13fr** [comment]
Hello,

You can download the last release, I fixed this bug :)

Max

**Comment by berto0** [comment]
I've been testing it and now if it updates.  Thank you.
