### ISSUE TITLE
Error prior to upgrading

### ISSUE THREAD

**Issue by marcgarciamarti** [max13fr/Airzonecloud-HomeAssistant#15]
Hello,

I've just simulated an upgrade, and I got this error:

```
Failed config
  General Errors: 
    - Platform error climate.airzonecloud - Integration 'airzonecloud' not found.
```

I've tried to add the string I saw in a different issue to the manifest file, with no positive effect either.

Anybody has any experience?

Thanks!

**Comment by gabrio79** [comment]
have you updated manifest.json with something like "version": "1.0" or downloading latest version?

**Comment by marcgarciamarti** [comment]
> have you updated manifest.json with something like "version": "1.0" or downloading latest version?
> 
> 

Adding the "version" string didn't work. Installing the current version did the trick :)

Thank you!!

**Comment by AESIR93** [comment]
> Hello,
> 
> I've just simulated an upgrade, and I got this error:
> 
> ```
> Failed config
>   General Errors: 
>     - Platform error climate.airzonecloud - Integration 'airzonecloud' not found.
> ```
> 
> I've tried to add the string I saw in a different issue to the manifest file, with no positive effect either.
> 
> Anybody has any experience?
> 
> Thanks!

Hey do you by any chance remember which string you were referencing here?
I've run into the same issue and I'm not having any luck fixing it.
Thanks!!
