### ISSUE TITLE
Doesn’t work anymore with new airzone api

### ISSUE THREAD

**Issue by plouf34** [max13fr/Airzonecloud-HomeAssistant#19]
Hello
Since this morning and the new version of Airzone cloud, the integration doesn’t work anymore.

**Comment by gabrio79** [comment]
Hello, what is not working?
Mine is fine...

Il Lun 19 Lug 2021, 23:04 plouf34 ***@***.***> ha scritto:

**Comment by joasara** [comment]
Nothing works. Restarting Home Assistant indicates that it cannot connect to AirzoneCloud. It happens since Airzone has modified its mobile APP.

**Comment by gabrio79** [comment]
could you please provide log, in order to check what happened?
sometime I have some some connection error, but is working

**Comment by joasara** [comment]
This is the error:
----------------------------
Este error se originó a partir de una integración personalizada.

Logger: custom_components.airzonecloud.climate
Source: custom_components/airzonecloud/climate.py:47
Integration: airzonecloud (documentation, issues)
First occurred: 9:47:00 (1 occurrences)
Last logged: 9:47:00

Unable to login to AirzoneCloud
------------------------------

If you want something more specific, tell me where to get it.

**Comment by gabrio79** [comment]
in my opinion is not a integration issue, ma login issue. try to create (via app) a new user, or verify permissions to current user. if I understood the new app, permission is now on single device/zone

**Comment by joasara** [comment]
It seems that neither.
I have created a new user and given the permissions. I have tried with the 3 there are (advanced, basic and administrator) and the errors remain the same.
Those users in the airzone app if they log in correctly and can act without problems.

**Comment by ukrolelo** [comment]
+1 Stopped workign yesterday.
Explanation:
https://github.com/max13fr/AirzoneCloud/issues/7

**Comment by joasara** [comment]
Do we know if it can be fixed?

**Comment by ukrolelo** [comment]
When some developer will get along, i am watching all airzones repositories in search on github and watching the update date. If somebody update it i will try it and report here :>

**Comment by ukrolelo** [comment]
I have sent an email again, i am trying API calls from a Postman app. getting errors
405 Not Allowed
unknw

**Comment by jd1900** [comment]
I've talked to them via email.

Right now, once updated, the web version doesn't work unless pointing to https://m.airzonecloud.com/
But they say that in the coming days the are re-enabling it back again.

**Comment by ukrolelo** [comment]
Thank you for info!

**Comment by jd1900** [comment]
> Thank you for info!
> Interesting i changed to m.airzonecloud.com in the repository and still was not working. Well lets wait and see :>

m.airzonecloud.com points to the new airzone cloud, not the old one, maybe that's why.

**Comment by ukrolelo** [comment]
yeah...

**Comment by oopptt** [comment]
Same behavior here, not working since a couple of days ago

**Comment by marcgarciamarti** [comment]
Same here. Interested to follow this issue.

**Comment by plouf34** [comment]
Normally it should have been resolved this week…

**Comment by damm301** [comment]
same here. not working since the latest app and api updates. 
(but also their app messed things up - although not a login issue, but showing unreasonable temperature and humidity readings, and controls are mixed up)

**Comment by plouf34** [comment]
Hello
No news?

**Comment by ukrolelo** [comment]
> Hello
> No news?

https://github.com/max13fr/AirzoneCloud/issues/7#issuecomment-884778908

**Comment by antoinevandenhurk** [comment]
Any progress? Hope that this can be fixed...
(I miss my automated tools for my Airzone unit)

**Comment by aimartin** [comment]
I hope this is fixed soon, I miss it too :)

> 
> 
> Any progress? Hope that this can be fixed...
> (I miss my automated tools for my Airzone unit)
Out of my curiosity, what kind of automations do you have for the Aircon?

**Comment by supertabouret** [comment]
Same problem for me. I hope you can fix it :)

**Comment by jrhbcn** [comment]
> Out of my curiosity, what kind of automations do you have for the Airzone?

I've got a couple of them just to notify me when AC is on and a window is opened for more than 5 minutes in the same room or when I leave the house and left it ON. Simple but effective!!

**Comment by oopptt** [comment]
yes, same for me, I have one detecting me or my partner leaving the house and after 5 minutes out all the airzone systems are turned OFF, very useful. You can also control your humidifiers by checking blueface humidity values. Now obviously that's not working, so I hope it could be fixed soon.

**Comment by supertabouret** [comment]
Still not working 😰

**Comment by marcgarciamarti** [comment]
Guys, it's August. Cut him some slack!

**Comment by aabafra** [comment]
Another one looking forward to it! 

Amazing integration by the way. Can't wait for it to start working again! I guess there is a lot of reverse engineering and work to do and as @marcgarciamarti said, these are not the most convenient dates for that.. 

Thanks and good luck

**Comment by gabrio79** [comment]
if I am not mistaken, the documentation has not yet come out ... how does @max13fr  develop ???

**Comment by supertabouret** [comment]
> if I am not mistaken, the documentation has not yet come out ... how does @max13fr develop ???

Not sure but here is the api guide i found. 
https://drive.google.com/file/d/1qBr5jXPaf8GSB86EdCzptl5cDoWbHEJ8/view?usp=sharing

Does it help ? If you find a way to update the code let us know !

**Comment by max13fr** [comment]
Hi,

Here more information on this issue : https://github.com/max13fr/AirzoneCloud/issues/7#issuecomment-896016442

Max

**Comment by jeromelebel** [comment]
Can you contact me?

**Comment by aabafra** [comment]
Any progress on this? No news since early Aug :(. I tried other integrations but no success on my webserver. Anyone who has solved the problem? Any recommendation? Many thanks

**Comment by marcgarciamarti** [comment]
> Any progress on this? No news since early Aug :(. I tried other integrations but no success on my webserver. Anyone who has solved the problem? Any recommendation? Many thanks

What other integrations did you try?

**Comment by aabafra** [comment]
> > Any progress on this? No news since early Aug :(. I tried other integrations but no success on my webserver. Anyone who has solved the problem? Any recommendation? Many thanks
> 
> What other integrations did you try?

My Airzone is 1 year old and I got it sold as something called "Werbserver".

I've tried this one: https://github.com/gpulido/homeassistant-airzone but I don't know either the class (Innobus, Aidoo or LocalAPI) nor the port. It seems that it's working for some people.

I've also tried this one: https://github.com/jrhbcn/HomeAssistant-airzone_local - seems to be a fork from max13fr but working locally. Haven't succeed either.

Regards

**Comment by ukrolelo** [comment]
I can confirm that this local airzone homeassistant custom components is working
https://github.com/gpulido/homeassistant-airzone
All is fine, lets hope it sticks this way smile

This is my settings:
climate:

platform: airzone
host: 192.168.x.x
port: 3000
device_id: 1
device_class: localapi

**Comment by plouf34** [comment]
Did you installed the python Airzone api for that?

**Comment by jrhbcn** [comment]
> I've also tried this one: https://github.com/jrhbcn/HomeAssistant-airzone_local - seems to be a fork from max13fr but working locally. Haven't succeed either.

I am the author of that, it is still a work in progress and not ready for the public sorry! However, I recommend to use as other have mentioned this repo https://github.com/gpulido/homeassistant-airzone as should do everything and more.

In my case local API is working but then my airzone webserver stops responding after 1-2 days. That has been consistent for weeks now. Anyone experiencing these problems? Is it stable for you?

**Comment by plouf34** [comment]
Your Airzone web server stop responding in any case (even with the Airzone application app) or just in HA?

**Comment by jrhbcn** [comment]
> Your Airzone web server stop responding in any case (even with the Airzone application app) or just in HA?
> I will not take the risk to break my Airzone heater / air conditioner

Any case, accessing local API directly using "curl" just stops responding. Contacted support and they said they were looking at it (but that was several weeks ago).

**Comment by aabafra** [comment]
> Did you installed the python Airzone api for that?

Same question here. I've just installed the custom component in HASS and was assuming that it should work just like this.

With "curl" on cmd, I get this error:

_curl -X POST http://192.168.X.XXX:3000/api/v1/hvac -H "Content-Type: application/json" -d "{\"systemId\":1, \"zoneId\":0}"

curl: (7) Failed to connect to 192.168.X.XXX port 3000: Connection refused_

My system is wireless (not wired as I've seen in some other people that got it working) and in the case I need to install something else, could someone shed some light on how to do it?

**Comment by jrhbcn** [comment]
@aabafra  I seem to recall (don't remember where I saw this) that the local API only worked for wired webserver (not wireless).

**Comment by aabafra** [comment]
> @aabafra I seem to recall (don't remember where I saw this) that the local API only worked for wired webserver (not wireless).

That's what I suspect.. I have also read it somewhere, but it's true that it's WIP and might have changed.

Just checked the invoice and my exact model is "airzone Flexa 3 ----- Flexa 3 6Z"

I might have to wait till a cloud solution.. @max13fr All my hopes are on you now :)

**Comment by oopptt** [comment]
@aabafra I will also try the local integration from gpulido, but AFAIK, for that solution to work we need a Raspberry Pi directly connected with your Airzone switchboard using RS485 to USB adaptor. So I'm waiting this connector to arrive to try that local connection. With that solution (if it works) you would have the local solution to manage the airzone with Home Assistant and also the Airzone cloud webserver just as a backup solution. Am I right guys or I'm missing something?

**Comment by aabafra** [comment]
> @aabafra I will also try the local integration from gpulido, but AFAIK, for that solution to work we need a Raspberry Pi directly connected to your Airzone switchboard using RS485 to USB adaptor. So I'm waiting this connector to arrive to try that local connection. With that solution (if it works) you would have the local solution to manage the airzone with Home Assistant and also the Airzone cloud webserver just as a backup solution. Am I right guys or I'm missing something?

Thanks! you made it pretty clear. 

It's a shame that it was working wirelessly through the cloud and now we've to do another work around using raspberries and additional coding layers to do exactly the same we already had. I hope that someone can get it again.. I'm really looking forward to it. If I see it takes too long, I may join you with the RS485 thing :D.

Thanks!

**Comment by ukrolelo** [comment]
> Did you installed the python Airzone api for that?

https://github.com/gpulido/homeassistant-airzone
Just this as per instruction

**Comment by antoinevandenhurk** [comment]
> > Did you installed the python Airzone api for that?
> 
> https://github.com/gpulido/homeassistant-airzone
> Just this as per instruction

Best ukrolelo,

[https://pypi.org/project/python-airzone/](url) describes a localapi for webserver: AZX6WEBSCLOUDC. 
I have this webserver: AZX6WSCLOUDDINR, and I can't get it working like you describred. Do you have a solution for me?

**Comment by ukrolelo** [comment]
Do you have any logs? you are using the one i am? Show settings.

**Comment by antoinevandenhurk** [comment]
> Do you have any logs? you are using the one i am? Show settings.

That's great, then I should be able to get this working. I followed installation documentation via [https://github.com/gpulido/homeassistant-airzone](url)

I can't get a connection via integration, so I put the above in climate.yaml. This is my configuration:
- platform: airzone
  host: 192.168.XXX.XX
  port: 5020
  device_id:
  device_class: "localapi"

See my airzone cloud system info screenshot: [https://ibb.co/k3gnTpS](url)

_I got this logging/error:_
Logger: airzone.localapi
Source: /usr/local/lib/python3.9/site-packages/airzone/localapi.py:62
First occurred: 10:22:40 (1 occurrences)
Last logged: 10:22:40

HTTPConnectionPool(host='192.168.XXX.XX', port=5020): Max retries exceeded with url: /api/v1/hvac (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f218f8bfc10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.9/http/client.py", line 1257, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1303, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1252, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1012, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.9/http/client.py", line 952, in send
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f218f8bfc10>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.XXX.XX', port=5020): Max retries exceeded with url: /api/v1/hvac (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f218f8bfc10>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airzone/localapi.py", line 52, in retrieve_state
    response = requests.post(url=self._API_ENDPOINT,
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.XXX.XX', port=5020): Max retries exceeded with url: /api/v1/hvac (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f218f8bfc10>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by ukrolelo** [comment]
![Screenshot_198](https://user-images.githubusercontent.com/60402662/133885075-b6b44db3-a04c-418a-9cc3-117714d5230d.png)
You have different ports and wrong quotes and no device ID.
Try with my settings again

**Comment by antoinevandenhurk** [comment]
I tried your suggestion, but unfortunately it doesn't work. (The device_id was in my config, but I had deleted too much information for this topic.) How did you find out which port number you needed?

**Comment by ukrolelo** [comment]
Well i read the API docs from airzone.
I tested the API with postman for http get+post and when i see that it was working i went to the airzone local addon.
But first try that regular API is working. Its pointles for you to test airzone local first as i see.

**Comment by antoinevandenhurk** [comment]
I'm not familiar with Postman, but I've seen a few youtube videos and would like to see if it makes me any wiser. Where can I find those Airzone API docs?

**Comment by antoinevandenhurk** [comment]
Sorry, I just see the API link in your post. (still a little early)

**Comment by antoinevandenhurk** [comment]
![error postman](https://user-images.githubusercontent.com/35188384/134817142-9f90bd58-ae1a-4a1e-8088-28941f883b26.png)

I can't make any connection with the gateway. It works fine via https://m.airzonecloud.com/, but I have no clue how to go on from here... I tried port scanning, that didn't give me any result. The documentation gives in example port number 5020, but in your situatie it was port 3000. Can someone give me a suggestion?

**Comment by ukrolelo** [comment]
If its not working and you don't see 3000 open port, you should ask you technician and say that local API is not working if they can enable it remotely. This was my case. They connected, done something, then i restart power on the airzone module and all good :)

**Comment by bvis** [comment]
The local API only is available in some "modern" hardware, it needs to be the model wifi 5G or the new hub.

If I'm not wrong in case you have an older hardware your only option is to connect via the AirzoneCloud API (it's what this component was doing until they changed the API version and broke the compatibility, as this is not an official component it can happen on any breaking change in the cloud API) or via sniffing protocol connecting a rbpi directly to the airzone component as mentioned in this thread.

**Comment by aabafra** [comment]
> The local API only is available in some "modern" hardware, it needs to be the model wifi 5G or the new hub.
> 
> If I'm not wrong in case you have an older hardware your only option is to connect via the AirzoneCloud API (it's what this component was doing until they changed the API version and broke the compatibility, as this is not an official component it can happen on any breaking change in the cloud API) or via sniffing protocol connecting a rbpi directly to the airzone component as mentioned in this thread.
> 
> It seems this differentiation is not clear enough for everybody and some people is trying to fix their problems with a mix of solutions that won't work.
> 
> This repo is about a component that connects via the Airzone Cloud API, my suggestion is that any alternative fix is addressed via links to their own repo for not to add here too much noise.

Is there any chance to use local API wirelessly? My hardware is 1 year old (Flexa 3.0). It was working prefectly throught Cloud and I'd like to avoid the rbpi thing..

**Comment by aabafra** [comment]
> technician

I've checked with a port scanner tool and only found port 22 (SSH) open. Who do you mean by "your technician"? Technical support? I've opened a ticket just in case.

**Comment by ukrolelo** [comment]
> > technician
> 
> I've checked with a port scanner tool and only found port 22 (SSH) open. Who do you mean by "your technician"? Technical support? I've opened a ticket just in case.

Well who installed the system. If you install by your self, then you need some technician who have knowledge to solve it

**Comment by Gotouille** [comment]
Hi,
Does someone know if there is progress on Airzone Cloud for Home Assistant ? Either from Max13fr him/herself or from another person/project ?

**Comment by aabafra** [comment]
I'm also interested on this.

> > Hi, Does someone know if there is progress on Airzone Cloud for Home Assistant ? Either from Max13fr him/herself or from another person/project ?
> 
> [max13fr/AirzoneCloud#7 (comment)](https://github.com/max13fr/AirzoneCloud/issues/7#issuecomment-908217084)

As far as I know, this solution only works through LOCAL API - either you need some of the specific models supporting it or install a raspberry pi doing that function.

What I would like to have again is a pure cloud integration, just having to introduce my Airzone cloud login. Really looking foward to it. @max13fr all our hopes are on you man

**Comment by gabrio79** [comment]
> > > Hi, Does someone know if there is progress on Airzone Cloud for Home Assistant ? Either from Max13fr him/herself or from another person/project ?
> > 
> > 
> > [max13fr/AirzoneCloud#7 (comment)](https://github.com/max13fr/AirzoneCloud/issues/7#issuecomment-908217084)
> 
> With this solution, I have only heat-cool or off possibilty? not Heat, Cool, fan... Before July, I could

is an half true: 
- real "state" is only on system, not on zone; and you can change it
- zone is only heat-cool or off, but you can use it to ON/OFF zone state
[here](https://github.com/gpulido/homeassistant-airzone/issues/13#issuecomment-914211571) more details

**Comment by gbuico** [comment]
Hi all. I lived in peace till a couple of days ago with my old API version and ignoring all this mess,
Then, silly me, I opened the Airzone app on the phone by mistake and the world fell on my head.
But, let me start with order.
My Airzone controller is a AZCE6IBPRO6 and the WebServer is a AZX6WEBSCLOUDC so, according to what I saw above I should be ok.
I'm not. The only open port of my WebServer is the 22... no access to the 3000.
When all this happened the firmware level of thw WebServer was 3.173 so, having seen that other people had to update their firmware to have it working, I called Airzone and they updated the firmware to 3.36.
I switched off the power to the Airzone to restart everything and tried again.... port 3000 is still closed.
I tried to email again Airzone to say that the port 3000 was closed and the local API not working... no answer so far, except a first nonsense answer suggesting to open the port 3000 in the provider access point.
Of course I'm doing my tests on the LAN, so, port 3000 is not open.
I checked both with NMAP and by trying to configure the integration.... connection refused.

I don't think I missed a step, but please, double check me and let me now if there is something I didn't think of.

Thanks for whatever hint...

**Comment by antoinevandenhurk** [comment]
I completely agree with your conclusion. This is where it ends for me too. Could it be a matter of switching a jumper on the board, or has the port been disabled via the firmware upgrade?

**Comment by gabrio79** [comment]
I have 2 systems, on the first one, all working on second one Local API doesn't worked, so I opened a mail ticket to support@airzone and they resolved.
Some days ago, I had so e problems, Local API doesn't works, i opened another ticket and the resolved again...
So, I can suggest you to write them again..
Where are you from? Could be Your local support not good? I'm from Italy

**Comment by gbuico** [comment]
@antoinevandenhurk ,
after seeing your post I went back to the documentation and checked if there was a switch related to this issue... 
Nothing at all.
In my case the port 3000 was already disabled when I was running formware 3.173 and continues to be disabled now on 3.36
To be sure I tried to run from command line "nmap -sT 192.168.1.18" and it confirmed that only port 22/tcp is open on that adapter..

**Comment by gbuico** [comment]
@gabrio79 ,
I'm living in France but I'm italian and I'm talking the italian support team.
As I said I wrote them saying that I had no access to port 3000 of the adapter and also asking to update the firmware.
They did the update to level 3.36 but gave me this answer concerning the port:
"Ad ogni modo per informazione, le dico che le porte si aprono direttamente dalle configurazioni avanzate del router, e questa operazione è eseguibile unicamente dall’utente, oppure dalla compagnia telefonica che presta il servizio di rete."
For the non italian friends, they gave an answer confusing the ports of the router with the ports of the appliance.

I kindly replied that I was talking of the port of the adapter and sent them the local-API manual to better explain my needs.
I got no answer so far to this second request, so I'll have to wait tomorrow towrite them again... unfortunately I don't have a phone number to call..  :(

**Comment by gbuico** [comment]
@gabrio79 
Good news.
Airzone answered and said that the local API was not loaded on the Webserver.
I immediatly reconfigured the integration in Home Assistant, make it point to the Webserver address, port 3000, localapi and.... voilà it worked at the first shot.
I'm very happy of their support... unfortunately there was a weekend in between.... but asking them the right question I got the right answer and very quickly

**Comment by antoinevandenhurk** [comment]
Yesterday I received a firmware upgrade to 3.36. I thought I understood that this would help me, but I still can't connect to the web server. I have performed the following actions:
Disabled the firewall on my Windows computer, so that no ports on my computer are blocked. Then I try the local api to post a request with Postman according to the manual, where I receive the error message: "Error: connect ECONNREFUSED 192.168.123.17:3000". According to Airzone, port 3000 should be open by default.
![image](https://user-images.githubusercontent.com/35188384/143294348-7a2fa995-d399-4d85-a3d7-e7e16b1d78b5.png)

**Comment by antoinevandenhurk** [comment]
In contrast, Portscan indicates that port 3000 is not open.
![image](https://user-images.githubusercontent.com/35188384/143295473-c4f12c76-6eca-415a-87cd-ea8b713ddfd4.png)

**Comment by gbuico** [comment]
@antoinevandenhurk , as I said above, when they updated my unit to 3.36 I also had port 3000 closed.
When I called them again they found that the localapi was not loaded on my unit and for that reason port 3000 was not open.
They corrected the issue without any additional firmware update

**Comment by antoinevandenhurk** [comment]
> 
![image](https://user-images.githubusercontent.com/35188384/143470900-1ea6f766-21e2-4a77-9d9b-86458cc0f560.png)
Unfortunately the local api doesn't seem to work for my device (AZX6WSCLOUDDINR).

**Comment by gbuico** [comment]
@antoinevandenhurk , yes... unfortunately localAPI is not available on Wireless devices...

**Comment by aabafra** [comment]
Hi guys,

I wrote Airzone support to find a way to connect through cloud (as before) and they gave me 2 ways that I think is worth exploring:

1/
The web api: https://developers.airzonecloud.com/docs/web-api/#auth It is an api where the credentials used are the user credentials. It is like when using the web but without the frontend part only direct requests. It is more intended for end users not for integrators or brands.

2/
The cloud api: https://developers.airzonecloud.com/docs/open-api/#post-/auth/oauth2/login It is one that is used for integrators, brands, companies. As I said the flow is a bit more complex because it adds an authentication layer before it can be used where we store the data of the integration that is being used, application name, description, etc.

__
For the latter, I receied some credentials that they created for me (client_id and client_secret).

Haven't had time to check it yet but I think that should be the way to get back what we once had.. the integration via cloud.

I will try to have it a look but would be great that someone with further knowledge gives it a try..

Sorry if all this is evident, it's just new to me.

**Comment by max13fr** [comment]
Hello,

They replied me finally two weeks ago with the new API documentation (first link).

I started the rewriting of airzonecloud library and this integration to Home assistant but it takes time as a lot of things have change.

Hope to provide a new working version before christmas perhaps sooner.

Max

**Comment by plouf34** [comment]
Take all the time that you need if you could deliver a version like before July ;-)

**Comment by aabafra** [comment]
> Hello,
> 
> They replied me finally two weeks ago with the new API documentation (first link).
> 
> I started the rewriting of airzonecloud library and this integration to Home assistant but it takes time as a lot of things have change.
> 
> Hope to provide a new working version before christmas perhaps sooner.
> 
> Max

Great news!! Really happy to hear this!!

**Comment by marcgarciamarti** [comment]
> Hello,
> 
> 
> 
> They replied me finally two weeks ago with the new API documentation (first link).
> 
> 
> 
> I started the rewriting of airzonecloud library and this integration to Home assistant but it takes time as a lot of things have change.
> 
> 
> 
> Hope to provide a new working version before christmas perhaps sooner.
> 
> 
> 
> Max

I couldn't be happier!!! Thank you @max13fr !!!

**Comment by antoinevandenhurk** [comment]
> Hello,
> 
> They replied me finally two weeks ago with the new API documentation (first link).
> 
> I started the rewriting of airzonecloud library and this integration to Home assistant but it takes time as a lot of things have change.
> 
> Hope to provide a new working version before christmas perhaps sooner.
> 
> Max

Hey Max,

That would be great, since my hardware isn't compatible for the local API.

**Comment by ukrolelo** [comment]
@max13fr wooohooooo

**Comment by max13fr** [comment]
Hello,

Just to keep you update, I just released a new version of the AirzoneCloud library using the official Airzone API : https://github.com/max13fr/AirzoneCloud

It's a huge step to get home assistant integration working again as it's the low level library used internally.

Max

**Comment by aabafra** [comment]
> Hello,
> 
> Just to keep you update, I just released a new version of the AirzoneCloud library using the official Airzone API : https://github.com/max13fr/AirzoneCloud
> 
> It's a huge step to get home assistant integration working again as it's the low level library used internally.
> 
> Max

Thanks a million Max, I’m sure you’ll get it. Looking forward to it, as many many people

**Comment by Gotouille** [comment]
Thanks a lot for your hard work

**Comment by mvillarejo** [comment]
great work @max13fr!

**Comment by plouf34** [comment]
Do you know when the new version for HA will be released?

**Comment by jfernandezgersol** [comment]
Hi @max13fr! Really cool that you are trying to keep updated both repos :) Thank you! If I can help you somehow with the release of a new version in this repo to support the new API, just let me know.

**Comment by tsenay** [comment]
Hello folks. 
I've implemented a working integration from this repo : [here](https://github.com/tsenay/Airzonecloud-HomeAssistant/releases/tag/0.1.1)
Enjoy!

**Comment by max13fr** [comment]
Hello,

Good news, I finally got the time to do all the changes needed.

Just upgrade to the new version (v1.1.1) and it should work fine.

Have fun, Max

**Comment by ukrolelo** [comment]
Wooohoooooooooooooooo Thank you!

**Comment by antoinevandenhurk** [comment]
It's working again, thank you very much!

**Comment by Neurohome** [comment]
> Hello,
> 
> Good news, I finally got the time to do all the changes needed.
> 
> Just upgrade to the new version (v1.1.1) and it should work fine.
> 
> Have fun, Max



Hi. You sed the new version of the airzonecloud integration on HA HACS?
