### ISSUE TITLE
Airzonecloud error Unable to login to AirzoneCloud

### ISSUE THREAD

**Issue by Tomcatnet** [max13fr/Airzonecloud-HomeAssistant#20]
cannot connect to cloud service

**Comment by plouf34** [comment]
This add on is depreciated. Author seems to not work work anymore on it. 
You have to use the local api.

**Comment by aabafra** [comment]
Really sorry to read that. I had reached that conclusion too as he doesn’t even answer when is mentioned. It’s a pity.. with cloud integration, there is no need to use a raspberry or equivalente that is a mess to me

**Comment by max13fr** [comment]
Hello,

Good news, Airzone finally released their new versions few weeks ago and I got the time to do all the changes needed.

Just use the new version (v1.1.1) and it should work fine.

Have fun Max
