### ISSUE TITLE
Unable to configure the integration 

### ISSUE THREAD

**Issue by garbovich** [max13fr/Airzonecloud-HomeAssistant#24]
Hi, First of all, thank you for the effort!!!
Today i installed airzone AZAI6WSCDA1 unit, everything is working great and i can access Airzone cloud and control my AC thru cloud
I installed the latest Airzonecloud integration as described and looks like everything is correct, no errors or warnings 

But i can see my AC unit in home assistance
Is there any option to debug what is wrong ? 

Thanks

**Comment by max13fr** [comment]
Hello,

You don't see any zones in home assistant or just the AC unit is missing ?

If first case, could you send me your Airzonecloud idents (set a temporary password before obviously) by mail (max13fr [at] yozo.fr) to allow me to check what is wrong ?

It is surely a specificity of your material.

Max

**Comment by garbovich** [comment]
Hi

I don't see the unit at all , no new device is added, if i set wrong
password i get notification that login to airzone cloud has failed, so
something is working.
Do you still need my airzone account ?

Thanks

Regards,

Gennady Garbovich

**Comment by garbovich** [comment]
Hi Again,

Just updated to latest version and i can now see the unit but its not
functional

Thanks

Regards,

Gennady Garbovich

**Comment by garbovich** [comment]
Attached error message that i am getting

Regards,

Gennady Garbovich

**Comment by garbovich** [comment]
Sorry about multiple messages,

I think photos can't be attached

Below is the error message i am getting whan trying to push any of the
buttons on climate


"Failed to call service climate/set hvac mode. Cannot find master device in
group Group(name;First Floor,
 installation;Home, id;61 cda8e73ac0ac6581 faf5)"

Thanks a lot

**Comment by garbovich** [comment]
Forgot to mention that i only have 1 zone. after 1.2.1 version HA finds the climate, but it's unavailable 

![Screenshot 2022-01-03 100514](https://user-images.githubusercontent.com/77881127/147909808-d73fde06-08e0-4d7d-8fb5-d62e5c44ef65.png)
![Screenshot 2022-01-03 100536](https://user-images.githubusercontent.com/77881127/147909817-97c874d5-accc-499f-8ae1-c49d4afc9287.png)

**Comment by garbovich** [comment]
After some debugging the issue is probably there:

In the Airzone Library there is a section to retrieve devices for each group

In the example the api should print:

Installation(name=Home)
  Group(name=System 1, installation=Home)
    **Device(name=Salon, is_connected=True, is_on=True, mode=heating, current_temp=20.9, target_temp=20.0, id=60f5cb990123456789abdce1, ws_id=AA:BB:CC:DD:EE:FF)
    Device(name=Ch parents, is_connected=True, is_on=False, mode=heating, current_temp=17.2, target_temp=18.0, id=60f5cb990123456789abdce2, ws_id=AA:BB:CC:DD:EE:FF)
    Device(name=Ch bebe, is_connected=True, is_on=False, mode=heating, current_temp=18.6, target_temp=19.5, id=60f5cb990123456789abdce3, ws_id=AA:BB:CC:DD:EE:FF)**

In my case (only one device) i am getting below:

Installation(name=Home)
Group(name=Daikin, installation=Home)

**And devices are missing** 

Thanks

**Comment by garbovich** [comment]
Issue resolved in v1.2.2
