### ISSUE TITLE
Deprecated function homeassistant.util.temperature

### ISSUE THREAD

**Issue by R1NEJ0** [max13fr/Airzonecloud-HomeAssistant#28]
Hi! I realized in log view that homeassistant.util.temperature function is deprecated, this weekends if I have time I will make some changes to use the new function.

I anyone got it please make a PR.

Thanks!!

**Comment by pgpana** [comment]
Hello R1NEJ0,

I tried to modify the original file without success.
Have you been able to fix It? 
If so could you share It with me?
Thanks in Advance for a feedback. Gianni

**Comment by R1NEJ0** [comment]
I'm very busy theses days, so a I could not try to fix it.

Here you go the official Web API:

https://developers.airzonecloud.com/docs/web-api/#overview

**Comment by elpeter25** [comment]
Made it work modifying climate.py like this:

![2023-03-06 14_35_28-HA J5005 NUC](https://user-images.githubusercontent.com/37652763/223125140-15a0d31b-6d19-4d0d-9069-1fc45b6afa33.png)

I can add the component but cannot use it, only show it :(

**Comment by max13fr** [comment]
Hello,

Sorry for the delay, free time is really missing.

Shoud be fixed with the v1.3.0.

Max
