### ISSUE TITLE
Cannot restart the system

### ISSUE THREAD

**Issue by maaper** [max13fr/Airzonecloud-HomeAssistant#29]
Hello, after following the steps I will try to reboot with the following message:

The system cannot restart because the configuration is not valid: Platform error climate.airzonecloud - Integration 'airzonecloud' not found.

Can someone help me with that?

**Comment by jesusvila** [comment]
Remove config part from configuration.yaml and restart. Once restarted, put again config in configuration.yaml and restart again.

**Comment by maaper** [comment]
Not sure what I did to solve it. I think that I force the stop of the container running in docker and restart it again. 
The point is that suddenly if found the Airzone controls on my home-assistant dashboard.

**Comment by marcos927** [comment]
Hello, same issue here but cannot not solve it removing config. Any other solution?
climate:

my config yaml
  - platform: airzonecloud
    username: XXXXX
    password: XXXXXXX

manifest
{
  "domain": "airzonecloud",
  "name": "Airzone Cloud",
  "documentation": "https://github.com/max13fr/Airzonecloud-HomeAssistant",
  "issue_tracker": "https://github.com/max13fr/Airzonecloud-HomeAssistant/issues",
  "dependencies": [],
  "after_dependencies": ["http"],
  "codeowners": ["@max13fr"],
  "version": "1.2.2",
  "requirements": ["AirzoneCloud==1.2.2"]
}

const
# #### CONF ####
CONF_USERNAME = "XXX@gmail.com"
CONF_PASSWORD = "XXXX"
