### ISSUE TITLE
Sistems name reset

### ISSUE THREAD

**Issue by gabrio79** [max13fr/Airzonecloud-HomeAssistant#3]
Hello,
first of all many thanks for your code, i love it...
since i installed your code, sometimes appen that sistems name are reset to default on AirZone server. Have you got same issue?

**Comment by max13fr** [comment]
Hi,

Sorry for delay, didn't see the notification.

Just had the same issue from "home" to "system_1", really strange.

I think it's a change from Airzone cloud after an update, I hope it shouldn't change anymore.

Max

**Comment by gabrio79** [comment]
I opened a tiket on Airzone at the same time, they told me that integration could starts system scan and names changes... and the investigates. Since days din't change anymore.
Many thanks again for you time & work
