### ISSUE TITLE
Not updating component state after Home Assistant upgrade to 2023.5.x

### ISSUE THREAD

**Issue by luigixx73** [max13fr/Airzonecloud-HomeAssistant#32]
Everything was working ok until I upgraded to 2023.5.3
You can interact from HA with the climate component as expected however if you manipulate the physical device using its panel, the HA component is not updated.
Checked at https://m.airzonecloud.com/    and it updates the state properly so I believe that the problem is in the update component / refresh function in the component that is not updating a regular intervals.

**Comment by max13fr** [comment]
Hello,

Sorry for the delay, free time is really missing.

Shoud be fixed with the v1.3.0.

Max
