### ISSUE TITLE
does not show up at integrations, so also no devices after installation

### ISSUE THREAD

**Issue by mamsterdam12** [max13fr/Airzonecloud-HomeAssistant#33]
hi,
I installed it

but is does not show up at integrations or shows any devices.

What to do? I am already using the local airzone but I also Have 1 aidoo (AZAI6WSCTOS) and that one is not supported in the local version.

**Comment by max13fr** [comment]
Hello,

This plugin is for airzone cloud version, if you're looking for a local integration you can check this official integration : https://www.home-assistant.io/integrations/airzone/

Max
