### ISSUE TITLE
not work after las update of HA

### ISSUE THREAD

**Issue by ElBielas** [max13fr/Airzonecloud-HomeAssistant#34]
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77 
First occurred: 14 de julio de 2023, 23:24:39 (2 occurrences) 
Last logged: 14 de julio de 2023, 23:24:39

Detected integration that uses temperature utility. This is deprecated since 2022.10 and will stop working in Home Assistant 2023.4, it should be updated to use unit_conversion.TemperatureConverter instead. Please report issue to the custom integration author for airzonecloud using this method at custom_components/airzonecloud/climate.py, line 151: return convert_temperature(
Detected integration that uses temperature utility. This is deprecated since 2022.10 and will stop working in Home Assistant 2023.4, it should be updated to use unit_conversion.TemperatureConverter instead. Please report issue to the custom integration author for airzonecloud using this method at custom_components/airzonecloud/climate.py, line 158: return convert_temperature(

Please, could you update the componente ???

Thanks very much

Best Regards

**Comment by danise76** [comment]
Like everyone, same message. Is this still maintained?

**Comment by max13fr** [comment]
Hello,

Sorry for the delay, free time is really missing.

Shoud be fixed with the v1.3.0.

Max
