### ISSUE TITLE
Error calling service climate/set_hvac_mode

### ISSUE THREAD

**Issue by rafabayona** [max13fr/Airzonecloud-HomeAssistant#4]
Hey, I've just installed this service to my Home Assistant and I thought it was working great as it list all my zones at home. However, as soon as I try to change anything (switching a zone on, changing temperature...) I get this message (translated from Spanish):

"Error calling service climate/set_hvac_mode
Expecting value: line 1 column 2 (char 1)"

Is it something I am doing wrong?

**Comment by max13fr** [comment]
Hi,

Perhaps it's a issue for your hardware ? What is your climate device and airzone webserver version (wifi or ethernet) ?

**Comment by max13fr** [comment]
Hi,

I add autoreconnect on expired token & improve errors message.

Try to upgrade and reopen this ticket if you're still have this issue.

Max
