### ISSUE TITLE
Humidity integration

### ISSUE THREAD

**Issue by gabrio79** [max13fr/Airzonecloud-HomeAssistant#7]
Hi max13fr, have you ever think to include humiduty information in your integration?

**Comment by max13fr** [comment]
Hi,

Just added current humidity in the last version, upgrade and it's should be fine.

Max

PS: Home Assistant seems to not display current humidity in the climate lovelace card but the data is available (you can see it in YOUR_HA_URL/developer-tools/state and selecting a zone)
