### ISSUE TITLE
Add support for dknwserver

### ISSUE THREAD

**Issue by ElBielas** [max13fr/Airzonecloud-HomeAssistant#8]
Hi could you add support to the dknwserver platform ? Many months ago speak about it, do you remember ? Thanks !!!

**Comment by max13fr** [comment]
Hi,

Yes sorry, didn't have many free time the last few months. I tried to work on it today, but the account test is not working anymore.
If you can send me temp ident to max13fr [at] yozo.fr, would allow me to continue the dev.

Max

**Comment by max13fr** [comment]
Here you go : https://github.com/max13fr/AirzonecloudDaikin-HomeAssistant

Max

**Comment by max13fr** [comment]
PS: the data refreshing is slow after an action but I cannot do anything, the lag is coming from airzone (device or website)

**Comment by ElBielas** [comment]
Thanks!!!!!!!!!!! I'll try to configure in HA this night. Again thanksssss

**Comment by mvillarejo** [comment]
Hello,
I give it a go and seems to work good for me.

Great work @max13fr !!
